### ISSUE TITLE
Support Pagination on `ListMicrogridDispatches`

### ISSUE THREAD

**Issue by thomas-nicolai-frequenz** [frequenz-floss/frequenz-api-dispatch#80] opened 2023-09-20 12:04 UTC
### What's needed?

Google [advises](https://cloud.google.com/apis/design/design_patterns.md#list_pagination) to use pagination by default on all list requests. If not being done early on introducing this later would be a breaking change.

### Proposed solution

Extend `ListMicrogridDispatches` rpc to use pagination by default:

```Diff
// Service providing operations related to dispatching microgrid components.
service MicrogridDispatchService {
  // Returns a list of all dispatches
-  rpc ListMicrogridDispatches(DispatchListRequest) returns (DispatchList);
+  rpc ListMicrogridDispatches(DispatchListRequest) returns (DispatchListResponse);
```
  
```Diff
// Message for listing dispatches for a given microgrid, and an optional filter
message DispatchListRequest {
  // The microgrid ID
  uint64 microgrid_id = 1;

  // Additional filter parameters
  DispatchFilter filter = 2;
  
+ // maximum number of results to be returned
+ int32 page_size = 3;

+ // identifies a specific page of the list results
+ string page_token = 4;
}
```

```Diff
// A list of dispatches
- message DispatchList {
+ message DispatchListResponse {
  // The dispatches
  repeated Dispatch dispatches = 1;

+ // The pagination token to retrieve the next page of results. 
+ // If the value is "", it means no further results for the request. Pass the value of response's 
+ // next_page_token in the subsequent ListMicrogridDispatches method call in page_token field.
+ string next_page_token = 2;
}
```

**Comment by Marenz** [comment] 2024-07-03 10:02
closing, duplicate of https://github.com/frequenz-floss/frequenz-api-dispatch/issues/165

**Closed as completed by Marenz** 2024-07-03 10:02 UTC
Labels: part:❓, priority:❓, type:enhancement
